name: zakkistore_sdk
description: Official Flutter/Dart SDK Client Library for Zakki Store B2B API Gateway.
version: 1.0.5
homepage: https://github.com/MrLow12/zakkistore-sdk-flutter
repository: https://github.com/MrLow12/zakkistore-sdk-flutter

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: ^0.13.0
